# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029b203b03c1519f229803d997a84078a93df035fcb421a3a7ef08adba96c03e5bc07b5c2f9fe2ab498c93eaa10c1974c5dcda17bb0f7790537eba3d2e3cbe7c

test:
  secret_key_base: 0d5842917f3b0a250b7937b5bb59d8316ba64cd4ae9a9a9cc3169125317ec610ce69c4acf113d77986570bf7e53a1fc0a0721642cb9d289d02834fd72cf5265d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
